# Publish all joint states ------------
joint_state_controller:
    type: joint_state_controller/joint_state_controller
    publish_rate: 50

# Position Controllers --------- for arm2.xacro ....
joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_servo1
    pid: {p: 700.0, i: 50.0, d: 70.0}
joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: servo1_shaft1
    pid: {p: 700.0, i: 50.0, d: 70.0}
joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: shaft1_link1
    pid: {p: 700.0, i: 50.0, d: 70.0}    

